DATA_INFO:
        DATA_ROOT: './FG3D/'
        MAX_NUM_VIEWS: 12
        IMAGE_SIZE: 224
        NUM_CLASSES: 13
        CLASSES: 'Airplane'
        NUM_GROUPS: 0
        GROUPS: ''

BACKBONE_INFO:
        ARCHITECTURE: 'RESNET18'
        FEATURE_DIM: 512

ENV_INFO:
        SEED: 1000 # options: [100, 1000, 10000, 100000, 1000000]
        DEVICE: 'cuda:0'
        NUM_WORKERS: 2

SV_INFO:
        SV_TYPE: 'CE' # options: [CE, KD, SB, HB, LS, DSB, DHB, SAT, LRT, PLC, SEAL, OLS, HPIQ, HS]
        SV_FLAG: 'TRAIN' # options: [TRAIN, TEST]
        SV_WEIGHT_PATH: './weight_sv/'
        SV_OUTPUT_PATH: './output_sv/'
        SV_TEST_WEIGHT: './weight_sv/CE.pt'
        SV_EPOCHS: 30
        SV_BS_TRAIN: 128
        SV_BS_TEST: 128
        SV_MOMENTUM: 0.9
        SV_WEIGHT_DECAY: 0.001 # 1e-3
        SV_LR_INIT: 0.01 # 1e-2

SOFT_LABEL_INFO:
        KD_T: 2 # options: [2, 2.5, 3, 3.5, 4]
        KD_ALPHA: 0.9
        BS_CHECKPOINT: 1
        SB_BETA: 0.5 # options: [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]
        HB_BETA: 0.95 # options: [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]
        LS_SMOOTH: 0.1
        DB_CHECKPOINT: 1
        DB_ALPHAS_F: [1., 2.]
        DB_BETAS_F: [2., 1.]
        DB_LAMBDAS_F: [0.5, 0.5]
        DB_MAX_LOSS_BOUND_F: 95
        DB_MIN_LOSS_BOUND_F: 5
        DB_LOSS_BOUND_F: 0.001 # 1e-3
        DB_RESOLUTION_F: 1000
        DB_MAX_ITERATION_F: 100
        DB_AVOID_ZERO_EPS_F: 0.000000000001 # 1e-12
        DB_EM_EPS_F: 0.0001 # 1e-4
        DB_NAN_EPS_F: 0.000000000001 # 1e-12
        SAT_CHECKPOINT: 4
        SAT_ALPHA: 0.9
        LRT_RETRO_EPOCH: 2
        LRT_UPDATE_EPOCH: 4
        LRT_INTERVAL_EPOCH: 6
        LRT_EVERY_N_EPOCH: 1
        LRT_DELTA_X_F: 1.2
        LRT_DELTA_Y_F: 0.02
        LRT_SOFT_EPS_F: 0.001 # 1e-3
        LRT_UPDATE_EPS_F: 0.0001 # 1e-4
        LRT_RHO_F: 0.9
        LRT_FLIP_EPS_F: 0.01 # 1e-2
        PLC_ROLL_WINDOW: 5
        PLC_WARM_UP: 2
        PLC_DELTA: 0.2 # options: [0.2, 0.3, 0.4, 0.5]
        PLC_STEP_SIZE: 0.05 # options: [0.05, 0.1, 0.2, 0.3]
        PLC_LRT_RATIO_F: 0.001 # 1e-3
        PLC_MAX_DELTA_F: 0.9
        SEAL_TIME: 2 # options: [1, 2, 3, 4, 5]
        OLS_ALPHA: 0.9 # options: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

MV_INFO:
        MV_TYPE: 'MVCNN_NEW' # options: [MVCNN_NEW, GVCNN, DAN, CVR, MVFN, SMVCNN, VSF]
        MV_FLAG: 'TRAIN' # options: [TRAIN, TEST, CM, COMPUTATION]
        MV_WEIGHT_PATH: './weight_mv/'
        MV_OUTPUT_PATH: './output_mv/'
        MV_TEST_WEIGHT: './weight_mv/DAN.pt'
        MV_EPOCHS: 50
        MV_BS_TRAIN: 32
        MV_BS_TEST: 32
        MV_MOMENTUM: 0.9
        MV_WEIGHT_DECAY: 0.001 # 1e-3
        MV_WARMUP_EPOCHS: 1
        MV_LR_INIT: 0.001 # 1e-3
        MV_LR_END: 0

FEATURE_AGGREGATION_INFO:
        GVCNN_M: 6
        DAN_H: 7 # options: [1, 2, 3, 4, 5, 6, 7, 8]
        DAN_NUM_HEADS_F: 1
        DAN_INNER_DIM_F: 2048
        DAN_DROPOUT_F: 0.1
        CVR_K: 3 # options: [2, 3, 4]
        CVR_LAMBDA: 1.0 # options: [0.1, 0.5, 1]
        CVR_NUM_HEADS_F: 8
        CVR_INNER_DIM_F: 2048
        CVR_NORM_EPS_F: 0.000001 # 1e-6
        CVR_OTK_HEADS_F: 1
        CVR_OTK_EPS_F: 0.05
        CVR_OTK_MAX_ITER_F: 100
        CVR_DROPOUT_F: 0
        CVR_COORD_DIM_F: 64
        SMVCNN_D: 512 # options: [16, 32, 64, 128, 256, 512]
        VSF_NUM_LAYERS: 4 # options: [2, 4, 6]
        VSF_WIDENING_FACTOR: 2 # options: [2, 4]
        VSF_NUM_HEADS_F: 8
        VSF_ATTENTION_DROPOUT_F: 0.1
        VSF_MLP_DROPOUT_F: 0.5

REPETITION: 500
TEST_T: 1
